### PR TITLE
Translation fr_FR

### PR DESCRIPTION
**Pull request by ajie62**
Hey, I was looking for some info about Markdown and found your Markdown tutorial. As it was only in English (Portuguese, Spanish) but not in French, I thought useful for people like me who look for info to translate it into French. I hope you'll like it! Don't hesitate to tell me if there are some things to add, modify or remove.

### CODE REVIEW

**Comment by luong-komorebi** [comment]
@ajie62  Thank you so much! I dont understand much of it (of course 😄), but I believe you are doing a great job.  The overall structure looks good.  Some words are still not translated, but not so much, for example `An image` , `A link`. I am still surprised how you found my guide since markdown are so popular that there are so many tutorials about it right now.  After all, thank you so much!

**Comment by ajie62** [comment]
@luongvo209 First I found your repository about LaTeX named "Begin-Latex-in-minutes", then I went to your GitHub profile and saw your repository about Markdown. It hold my interest, so I read it (in English) and found out there was no French version of it. Even though your tutorial isn't as famous as others, I guess some might reach it and be disturbed because it's not in French. 😃 By the way, thanks! While translating it, I learn two or three good things about MD. Don't hesitate to get in touch if you want me to take a look at a project for a French translation.

**Comment by luong-komorebi** [comment]
@ajie62 Thank you for your attitude. You really light up my day 😄 . 
  
Most of my projects now aren't in really urgent need of translation. But I think there are many others on Github that needs your help. Keep up the good work.

**Comment by ajie62** [comment]
Thanks! I'm not very familiar with GitHub, so I'm doing my best to contribute to projects, even though I'm not giving help with the code yet. I submitted another PR. Let me know if everything is ok! 😄

**Pull request merged**
