### PR TITLE
 Finish translation pt-BR

### PR DESCRIPTION
**Pull request by 0xHericles**
Add a new version on portuguese, brazilian.
complete file

### CODE REVIEW

**Comment by luong-komorebi** [comment]
HI @hericlesme , is this pull request the same as  #2 ?

**Comment by 0xHericles** [comment]
No, in this pull, I  finished translating the whole text. I sent the # 2 accidentally, pardon.

**Comment by luong-komorebi** [comment]
@hericlesme I alr merged #2. Can you pls resolve the conflicts 😭

**Comment by 0xHericles** [comment]
@LewisVo Yep! Sorry for this. 😂😭

**Comment by 0xHericles** [comment]
@LewisVo All right, I'm sorry again. :laughing:

**Comment by luong-komorebi** [comment]
Thank you so much @hericlesme . Wish you all the best!

**Pull request merged**
