### PR TITLE
Some translation fixes & add my name/URL

### PR DESCRIPTION
**Pull request by Ronkiro**
There were some untranslated words, or wrongly translated.
Just a fix to those words.

### CODE REVIEW

**Review by luong-komorebi — COMMENTED** [review]
@hericlesme Can you help take a look at this? I m not fluent in pt-BR so it would be great if you can share some insights. This would be automatically merged if no response from @hericlesme  in one week.

**Comment by luong-komorebi** [comment]
@Ronkiro Thank you for the suggestion. Really appreciate your time working on these fixes

**Comment by 0xHericles** [comment]
@luong-komorebi @Ronkiro sure!

**Review by 0xHericles — APPROVED** [review]

**Comment by 0xHericles** [comment]
@Ronkiro Thank you! :tada:

**Comment by Ronkiro** [comment]
Np! It's a pleasure for me to collaborate with the community too. Thank you guys for the attention!

**Pull request merged**
